'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.1
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LCARS_Login_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_error", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property academy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("academy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property autorisierungscode() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("autorisierungscode", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property autorisierungscode_erforderlich() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("autorisierungscode_erforderlich", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property be() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("be", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property be1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("be1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property beep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property beepbeepbeep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beepbeepbeep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property befehl() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("befehl", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property besteatigt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("besteatigt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property codefalse() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("codefalse", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property falsepass() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("falsepass", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property hauptenergie_verschlüsselt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hauptenergie_verschlüsselt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property keinZugang() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("keinZugang", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Kommandoautorisation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Kommandoautorisation", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property lcars_events_voicereco_ok() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("lcars_events_voicereco_ok", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newuser() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("newuser", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property numbers_origin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("numbers_origin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scanleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scanright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sicherheitscode() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sicherheitscode", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property stiabdruck_berechtigungscode() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("stiabdruck_berechtigungscode", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property voice_input_sc() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("voice_input_sc", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property zugang_genemigt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("zugang_genemigt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property zugang_hergestellt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("zugang_hergestellt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property zugang_verweigert() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("zugang_verweigert", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
